/**
 * Auto-generated TypeScript types from FastAPI OpenAPI schema.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is generated by running: npm run generate:types
 * (Requires the backend to be running at http://localhost:8000)
 *
 * Usage:
 *   import type { components } from "@/types/generated";
 *   type User = components["schemas"]["User"];
 *   type Program = components["schemas"]["Program"];
 *
 * Migration strategy:
 *   - Types in this file are the source of truth for API payloads
 *   - Manual types in sibling files (user.ts, program.ts, client.ts) should
 *     gradually migrate to re-exporting from this generated file
 *   - Frontend-specific extensions (UI state, computed fields) remain manual
 */

// Placeholder until generation is run
// Run: cd frontend && npm run generate:types

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface paths {
  // Will be populated by openapi-typescript
}

export interface components {
  schemas: Record<string, never>;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface operations {
  // Will be populated by openapi-typescript
}
