import {
  LayoutDashboard,
  Users,
  Handshake,
  UserCog,
  FolderKanban,
  PackageCheck,
  ClipboardList,
  CheckSquare,
  ShieldCheck,
  Timer,
  AlertTriangle,
  ScrollText,
  Scale,
  BarChart3,
  Star,
  CalendarClock,
  MessageSquare,
  Bell,
  Settings,
  Briefcase,
  Kanban,
  FileCheck,
  BadgeCheck,
  DollarSign,
  Trash2,
  ShieldAlert,
  ClipboardCheck,
  ThumbsUp,
  LayoutTemplate,
  Lock,
  SlidersHorizontal,
  PhoneCall,
} from "lucide-react";
import type { PortalNavConfig } from "@/types/navigation";

const MD = "managing_director";
const RM = "relationship_manager";
const COORD = "coordinator";
const FIN = "finance_compliance";

export const dashboardNavConfig: PortalNavConfig = {
  brandTitle: "AMG Portal",
  collapsible: "icon",
  groups: [
    {
      label: "Main",
      items: [
        {
          title: "Dashboard",
          href: "/",
          icon: LayoutDashboard,
          tooltip: "Dashboard",
        },
      ],
    },
    {
      label: "People",
      items: [
        {
          title: "Clients",
          href: "/clients",
          icon: Users,
          tooltip: "Clients",
          roles: [MD, RM, COORD],
        },
        {
          title: "Partners",
          href: "/partners",
          icon: Handshake,
          tooltip: "Partners",
          roles: [MD, RM, COORD],
        },
        {
          title: "Workload",
          href: "/workload",
          icon: Briefcase,
          tooltip: "Staff Workload",
          roles: [MD, RM, COORD],
        },
        {
          title: "Users",
          href: "/users",
          icon: UserCog,
          tooltip: "Users",
          roles: [MD],
        },
      ],
    },
    {
      label: "Operations",
      items: [
        {
          title: "Programs",
          href: "/programs",
          icon: FolderKanban,
          tooltip: "Programs",
        },
        {
          title: "Task Board",
          href: "/tasks",
          icon: Kanban,
          tooltip: "Task Board",
          roles: [MD, RM, COORD],
        },
        {
          title: "Deliverables",
          href: "/deliverables",
          icon: PackageCheck,
          tooltip: "Deliverables",
          roles: [MD, RM, COORD],
        },
        {
          title: "Assignments",
          href: "/assignments",
          icon: ClipboardList,
          tooltip: "Assignments",
          roles: [MD, RM, COORD],
        },
        {
          title: "Capability Reviews",
          href: "/capability-reviews",
          icon: ClipboardCheck,
          tooltip: "Capability Reviews",
          roles: [MD, RM, COORD, FIN],
        },
      ],
    },
    {
      label: "Oversight",
      items: [
        {
          title: "KYC",
          href: "/kyc",
          icon: BadgeCheck,
          tooltip: "KYC Verification",
          roles: [MD, FIN, RM],
          subItems: [
            { title: "Dashboard", href: "/kyc" },
            { title: "Verifications", href: "/kyc/verifications" },
            { title: "Alerts", href: "/kyc/alerts" },
            { title: "Reports", href: "/kyc/reports" },
          ],
        },
        {
          title: "Approvals",
          href: "/approvals",
          icon: CheckSquare,
          tooltip: "Approvals",
          roles: [MD, FIN],
        },
        {
          title: "Budget Approvals",
          href: "/budget-approvals",
          icon: DollarSign,
          tooltip: "Budget Approvals",
          roles: [MD, RM, FIN],
        },
        {
          title: "Compliance",
          href: "/compliance",
          icon: ShieldCheck,
          tooltip: "Compliance",
          roles: [MD, FIN],
        },
        {
          title: "Certificates",
          href: "/certificates",
          icon: FileCheck,
          tooltip: "Clearance Certificates",
          roles: [MD, FIN, RM, COORD],
        },
        {
          title: "SLA Tracking",
          href: "/sla",
          icon: Timer,
          tooltip: "SLA Tracking",
          roles: [MD, RM, COORD],
        },
        {
          title: "Escalations",
          href: "/escalations",
          icon: AlertTriangle,
          tooltip: "Escalations",
        },
        {
          title: "Audit Logs",
          href: "/audit-logs",
          icon: ScrollText,
          tooltip: "Audit Logs",
          roles: [MD, FIN],
        },
        {
          title: "Decisions",
          href: "/decisions",
          icon: Scale,
          tooltip: "Decisions",
          roles: [MD, RM],
        },
        {
          title: "Deletion Requests",
          href: "/deletion-requests",
          icon: Trash2,
          tooltip: "Deletion Requests",
          roles: [MD, FIN],
        },
        {
          title: "Access Audits",
          href: "/access-audits",
          icon: ShieldAlert,
          tooltip: "Access Audits",
          roles: [MD, FIN],
        },
        {
          title: "Cert Templates",
          href: "/certificates/templates",
          icon: LayoutTemplate,
          tooltip: "Certificate Templates",
          roles: [MD, FIN],
        },
      ],
    },
    {
      label: "Insights",
      items: [
        {
          title: "Analytics",
          href: "/analytics",
          icon: BarChart3,
          tooltip: "Analytics",
          roles: [MD, RM],
        },
        {
          title: "Partner Performance",
          href: "/analytics/partner-performance",
          icon: Star,
          tooltip: "Partner Performance",
          roles: [MD, RM],
        },
        {
          title: "Report Schedules",
          href: "/reports/schedules",
          icon: CalendarClock,
          tooltip: "Report Schedules",
          roles: [MD, RM],
        },
        {
          title: "RM Portfolio",
          href: "/reports/rm-portfolio",
          icon: Briefcase,
          tooltip: "RM Portfolio Report",
          roles: [MD, RM],
        },
        {
          title: "Escalation Log",
          href: "/reports/escalation-log",
          icon: AlertTriangle,
          tooltip: "Escalation Log Report",
          roles: [MD, RM, COORD, FIN],
        },
        {
          title: "Compliance Audit",
          href: "/reports/compliance",
          icon: ShieldCheck,
          tooltip: "Compliance Audit Report",
          roles: [MD, FIN],
        },
        {
          title: "NPS Surveys",
          href: "/analytics/nps",
          icon: ThumbsUp,
          tooltip: "NPS Surveys",
          roles: [MD, RM],
        },
      ],
    },
    {
      label: "Communication",
      items: [
        {
          title: "Messages",
          href: "/communications",
          icon: MessageSquare,
          tooltip: "Messages",
        },
        {
          title: "Notifications",
          href: "/notifications",
          icon: Bell,
          tooltip: "Notifications",
        },
        {
          title: "Comm Templates",
          href: "/communications/templates",
          icon: LayoutTemplate,
          tooltip: "Communication Templates",
          roles: [MD, RM, COORD],
        },
        {
          title: "Comm Log",
          href: "/communications/log",
          icon: PhoneCall,
          tooltip: "Communication Audit Log",
          roles: [MD, RM, COORD, FIN],
        },
      ],
    },
    {
      label: "Settings",
      items: [
        {
          title: "Settings",
          href: "/settings",
          icon: Settings,
          tooltip: "Settings",
        },
        {
          title: "Security",
          href: "/settings/security",
          icon: Lock,
          tooltip: "Security Settings",
        },
        {
          title: "Budget Thresholds",
          href: "/settings/budget-thresholds",
          icon: SlidersHorizontal,
          tooltip: "Budget Approval Thresholds",
          roles: [MD],
        },
      ],
    },
  ],
};
