/**
 * Dashboard export utilities — capture dashboard DOM as PDF or PNG.
 */

import html2canvas from "html2canvas-pro";
import { jsPDF } from "jspdf";

export interface ExportOptions {
  format: "pdf" | "png";
  includeHeader?: boolean;
  title?: string;
  userName?: string;
}

const EXPORT_SCALE = 2; // Higher quality capture
const PDF_MARGIN = 20; // mm

/**
 * Capture a DOM element as a canvas using html2canvas.
 */
async function captureElement(element: HTMLElement): Promise<HTMLCanvasElement> {
  return html2canvas(element, {
    scale: EXPORT_SCALE,
    useCORS: true,
    allowTaint: true,
    backgroundColor: "#ffffff",
    logging: false,
    // Ignore interactive elements that shouldn't appear in exports
    ignoreElements: (el) => {
      return el.hasAttribute("data-export-ignore");
    },
  });
}

/**
 * Build a header canvas with title, user name, and export timestamp.
 */
function buildHeaderCanvas(
  width: number,
  title: string,
  userName: string,
): HTMLCanvasElement {
  const headerHeight = 100 * EXPORT_SCALE;
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = headerHeight;
  const ctx = canvas.getContext("2d")!;

  // Background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, headerHeight);

  // AMG branding bar
  ctx.fillStyle = "#8B4513";
  ctx.fillRect(0, 0, width, 4 * EXPORT_SCALE);

  // Title
  ctx.fillStyle = "#8B4513";
  ctx.font = `bold ${18 * EXPORT_SCALE}px Georgia, serif`;
  ctx.fillText("AMG Dashboard Export", 20 * EXPORT_SCALE, 35 * EXPORT_SCALE);

  // Subtitle
  ctx.fillStyle = "#666666";
  ctx.font = `${11 * EXPORT_SCALE}px -apple-system, BlinkMacSystemFont, sans-serif`;
  ctx.fillText(title, 20 * EXPORT_SCALE, 55 * EXPORT_SCALE);

  // Timestamp and user
  const timestamp = new Date().toLocaleString("en-GB", {
    dateStyle: "long",
    timeStyle: "short",
  });
  ctx.fillText(
    `Generated by ${userName} · ${timestamp}`,
    20 * EXPORT_SCALE,
    72 * EXPORT_SCALE,
  );

  // Separator line
  ctx.strokeStyle = "#D2691E";
  ctx.lineWidth = EXPORT_SCALE;
  ctx.beginPath();
  ctx.moveTo(20 * EXPORT_SCALE, 85 * EXPORT_SCALE);
  ctx.lineTo(width - 20 * EXPORT_SCALE, 85 * EXPORT_SCALE);
  ctx.stroke();

  return canvas;
}

/**
 * Merge a header canvas and content canvas vertically.
 */
function mergeCanvases(
  header: HTMLCanvasElement,
  content: HTMLCanvasElement,
): HTMLCanvasElement {
  const merged = document.createElement("canvas");
  merged.width = content.width;
  merged.height = header.height + content.height;

  const ctx = merged.getContext("2d")!;
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, merged.width, merged.height);
  ctx.drawImage(header, 0, 0);
  ctx.drawImage(content, 0, header.height);

  return merged;
}

/**
 * Export dashboard element as PNG — triggers a download.
 */
async function exportPNG(
  canvas: HTMLCanvasElement,
  filename: string,
): Promise<void> {
  const dataUrl = canvas.toDataURL("image/png");
  const link = document.createElement("a");
  link.download = filename;
  link.href = dataUrl;
  link.click();
}

/**
 * Export dashboard element as multi-page PDF — triggers a download.
 * Handles long dashboards by splitting across pages.
 */
async function exportPDF(
  canvas: HTMLCanvasElement,
  filename: string,
): Promise<void> {
  const imgWidth = 210 - 2 * PDF_MARGIN; // A4 width minus margins (mm)
  const pageHeight = 297 - 2 * PDF_MARGIN; // A4 height minus margins (mm)

  // Scale canvas to fit PDF width
  const ratio = imgWidth / (canvas.width / EXPORT_SCALE);
  const imgHeight = (canvas.height / EXPORT_SCALE) * ratio;

  const pdf = new jsPDF("p", "mm", "a4");
  let position = 0;
  let pageNum = 0;

  while (position < imgHeight) {
    if (pageNum > 0) {
      pdf.addPage();
    }

    // Slice the canvas for this page
    const sourceY = (position / ratio) * EXPORT_SCALE;
    const sourceHeight = Math.min(
      (pageHeight / ratio) * EXPORT_SCALE,
      canvas.height - sourceY,
    );

    const pageCanvas = document.createElement("canvas");
    pageCanvas.width = canvas.width;
    pageCanvas.height = sourceHeight;

    const ctx = pageCanvas.getContext("2d")!;
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
    ctx.drawImage(
      canvas,
      0,
      sourceY,
      canvas.width,
      sourceHeight,
      0,
      0,
      canvas.width,
      sourceHeight,
    );

    const pageImgData = pageCanvas.toDataURL("image/png");
    const sliceHeight = (sourceHeight / EXPORT_SCALE) * ratio;
    pdf.addImage(pageImgData, "PNG", PDF_MARGIN, PDF_MARGIN, imgWidth, sliceHeight);

    // Footer on each page
    pdf.setFontSize(7);
    pdf.setTextColor(153, 153, 153);
    pdf.text(
      "Confidential — AMG Portal",
      PDF_MARGIN,
      297 - 8,
    );
    pdf.text(
      `Page ${pageNum + 1}`,
      210 - PDF_MARGIN,
      297 - 8,
      { align: "right" },
    );

    position += pageHeight;
    pageNum++;
  }

  pdf.save(filename);
}

/**
 * Main export function — captures the dashboard and triggers download.
 */
export async function exportDashboard(
  containerSelector: string,
  options: ExportOptions,
): Promise<void> {
  const container = document.querySelector(containerSelector) as HTMLElement;
  if (!container) {
    throw new Error(`Dashboard container not found: ${containerSelector}`);
  }

  const contentCanvas = await captureElement(container);

  let finalCanvas = contentCanvas;

  if (options.includeHeader !== false) {
    const headerCanvas = buildHeaderCanvas(
      contentCanvas.width,
      options.title ?? "Portfolio Overview",
      options.userName ?? "Unknown User",
    );
    finalCanvas = mergeCanvases(headerCanvas, contentCanvas);
  }

  const timestamp = new Date().toISOString().slice(0, 10);
  const baseName = `amg-dashboard-${timestamp}`;

  if (options.format === "pdf") {
    await exportPDF(finalCanvas, `${baseName}.pdf`);
  } else {
    await exportPNG(finalCanvas, `${baseName}.png`);
  }
}
